export const textos = {
  email: "E-mail",
  senha: "Senha",
  entrar: "Entrar",
  cadastrar: "Cadastrar",
  recuperar: "Recuperar senha",
  nome: "Nome",
  cpf: "CPF",
  inserir: "Inserir Foto",
  modelo: "Marca e modelo do veículo",
  placa: "Placa do veículo",
  adicionar: "Adicionar Imagem",
  alterar: "Alterar Imagem",
  embarque: "Embarque",
  desembarque: "Desembarque",
  gps: "gps",
  finalizar: "Finalizar",
  parabéns: "Parabéns",
  corrida: "Corrida finalizada com sucesso!",
  fazermais:"Fazer mais corridas",
  finance:"Financeiro",
  today:"Hoje",
};
